[package]
authors = ["The Rust Project Developers"]
name = "panic_unwind"
version = "0.0.0"

[lib]
path = "lib.rs"
test = false
bench = false
doc = false

[dependencies]
unwind = { path = "../libunwind" }
